version: '2'
services:
  ansibleuidata:
    build: .
    command: "true"
    volumes:
      - ./src/ansible-dyninv-api:/data/api:rw
      - ./src/ansible-dyninv-api-ui:/data/ui:rw

  nginx:
    image: nginx:1.13.0
    ports:
      - "8080:80"
      - "8081:81"
    volumes_from:
      - ansibleuidata
    depends_on:
      - fpm
    volumes:
      - ./nginx/ui.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/api.conf:/etc/nginx/conf.d/api.conf
      - ./api/var/jwt:/data/api/var/jwt
      - ./ui/config.js:/data/ui/js/config.js

  fpm:
    build: fpm/
    depends_on:
      - db
    volumes_from:
      - ansibleuidata
    volumes:
      - ./api/var/jwt:/data/api/var/jwt
      - ./api/start.sh:/data/start.sh
    entrypoint: /data/start.sh
    environment:
      - ANSIBLE_REST_ADMIN_USER=superadmin
      - ANSIBLE_REST_ADMIN_EMAIL=admin@foo.bar
      - ANSIBLE_REST_ADMIN_PASS=v3rys3cr3t
      # needed for startup script
      - MYSQL_ROOT_PASSWORD=v3rys3cr3t
      - MYSQL_DATABASE=ansible
      - MYSQL_USER=ansible
      - MYSQL_PASSWORD=ansibles3cr3tpassw0rd
      - API_SECRET_TOKEN=ThisTokenIsNotSoSecretChangeIt

  db:
    image: mariadb:10.1
    environment:
      - MYSQL_ROOT_PASSWORD=v3rys3cr3t
      - MYSQL_DATABASE=ansible
      - MYSQL_USER=ansible
      - MYSQL_PASSWORD=ansibles3cr3tpassw0rd
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
